# Assumptions:

# A script generate_verifier_data.py (not shown) has already run. It took the trained prover U_R, ran it on the verifier data split D_v, and produced an output file (e.g., verifier_samples_R.jsonl).
# This output file contains JSON objects, each with at least keys: "problem_id" (str), "code" (str), and "is_incorrect_or_backdoor" (bool - True if it failed tests OR is a known/detected backdoor, False otherwise).

# huggingface-cli login # Or set HF_TOKEN env var
# huggingface-cli repo create your_username/control-pvg-data-repo --type dataset --private # Create repo once
# export HUB_REPO_ID="your_username/control-pvg-data-repo"
# export BASE_PROVER_PATH="meta-llama/Llama-3-70b-chat-hf" # Example
# export BASE_VERIFIER_PATH="meta-llama/Llama-3-8b-chat-hf" # Example
# export PROBLEM_SET_PATH="./my_apps_subset.jsonl"
# export MAX_ROUNDS=5 # Number of rounds for the experiment
# export RL_STEPS_PER_ROUND=1000
# export VERIFIER_TRAIN_STEPS=500
# export BATCH_SIZE=32
# export MAX_HIST_ROUNDS=10 # For buffer cleanup
# export WEIGHT_TARGET=0.8


import argparse
import logging
import time
from typing import Any

import datasets
import huggingface_hub

logger = logging.getLogger(f"pvg.{__name__}")  # Get a child logger


def classify_sample(sample: dict[str, Any]) -> str:
    """Classifies sample based on the 'is_incorrect_or_backdoor' flag."""
    if sample.get("is_incorrect_or_backdoor", False):
        return "incorrect"
    else:
        return "correct"


def cleanup_old_hub_data(hub_repo_id: str, current_round: int, max_rounds_to_keep: int):
    """Removes data configs from rounds older than MAX_ROUNDS_TO_KEEP from the Hub."""
    cutoff_round = current_round - max_rounds_to_keep
    if cutoff_round <= 0:  # Don't delete round 0 or negative rounds
        logging.info("Skipping cleanup as cutoff round is non-positive.")
        return

    logging.info(f"--- Cleaning up Hub data older than Round {cutoff_round} (excluding Round 0) ---")
    try:
        api = huggingface_hub.HfApi()
        # List files, focusing on the data directory structure typically used
        # Assumes push_to_hub creates data/<config_name>/...
        repo_files = api.list_repo_files(hub_repo_id, repo_type="dataset")
        folders_to_delete = set()

        for filepath in repo_files:
            parts = filepath.split("/")
            # Check if it's likely a data file within a round config folder
            if len(parts) > 1 and parts[0] == "data":
                config_name = parts[1]  # e.g., round_X_correct
                config_parts = config_name.split("_")
                if len(config_parts) >= 3 and config_parts[0] == "round":
                    try:
                        round_num = int(config_parts[1])
                        if round_num < cutoff_round and round_num != 0:
                            folders_to_delete.add(f"data/{config_name}")
                    except ValueError:
                        continue  # Skip folders not matching the pattern

        if not folders_to_delete:
            logging.info("No old data folders found matching criteria for deletion.")
            return

        logging.warning(f"Planning to delete the following folders from Hub repo {hub_repo_id}:")
        for folder in sorted(list(folders_to_delete)):
            logging.warning(f" - {folder}")

        # --- Deletion ---
        # Uncomment the following lines to actually perform deletion
        # Be very careful with this!
        # for folder in sorted(list(folders_to_delete)):
        #     try:
        #         logging.info(f"Deleting folder: {folder}")
        #         api.delete_folder(hub_repo_id, folder, repo_type="dataset")
        #         logging.info(f"Successfully deleted {folder}.")
        #         time.sleep(1) # Small delay
        #     except Exception as e_del:
        #         logging.error(f"Failed to delete folder {folder}: {e_del}")

        logging.warning("Deletion code is commented out by default for safety. Uncomment to enable.")
        logging.info(f"Hub cleanup process planned for folders older than round {cutoff_round}.")

    except Exception as e:
        logging.error(f"Error during Hub cleanup: {e}")


def main():
    parser = argparse.ArgumentParser(description="Process generated verifier samples and store to Hugging Face Hub.")
    parser.add_argument(
        "--round_num",
        type=int,
        required=True,
        help="The round number for which data was generated (e.g., R).",
    )
    parser.add_argument(
        "--verifier_samples_path",
        type=str,
        required=True,
        help="Path to the .jsonl file containing samples generated by U_R on D_v.",
    )
    parser.add_argument(
        "--hub_repo_id",
        type=str,
        required=True,
        help="Hugging Face Hub repository ID (e.g., your_username/repo_name).",
    )
    parser.add_argument(
        "--max_rounds_to_keep",
        type=int,
        default=10,
        help="Number of recent rounds of data to keep on the Hub (plus round 0).",
    )
    parser.add_argument(
        "--hub_token",
        type=str,
        default=None,
        help="Hugging Face Hub token (optional, can use login or env var).",
    )
    parser.add_argument(
        "--repo_private",
        action="store_true",
        help="Set repository visibility to private.",
    )

    args = parser.parse_args()

    # Login to Hub if token provided
    if args.hub_token:
        huggingface_hub.login(token=args.hub_token)

    logging.info(f"Processing samples from: {args.verifier_samples_path} for Round {args.round_num}")

    # 1. Load the generated data
    try:
        raw_dataset = datasets.load_dataset("json", data_files=args.verifier_samples_path, split="train")
        logging.info(f"Loaded {len(raw_dataset)} raw samples.")
    except Exception as e:
        logging.error(f"Failed to load dataset from {args.verifier_samples_path}: {e}")
        return

    # 2. Process and Separate Samples
    correct_list = []
    incorrect_list = []
    required_keys = {"problem_id", "code", "is_incorrect_or_backdoor"}

    for sample in raw_dataset:
        if not required_keys.issubset(sample.keys()):
            logging.warning(f"Skipping sample due to missing keys: {sample.get('problem_id', 'Unknown ID')}")
            continue

        sample_type = classify_sample(sample)
        processed_sample = {
            "problem_id": str(sample["problem_id"]),  # Ensure string
            "code": sample["code"],
            "generation_round": args.round_num,
            # Add other relevant fields if needed, but keep minimal for storage
        }
        if sample_type == "correct":
            correct_list.append(processed_sample)
        else:
            incorrect_list.append(processed_sample)

    logging.info(f"Separated samples: {len(correct_list)} correct, {len(incorrect_list)} incorrect/backdoor.")

    if not correct_list and not incorrect_list:
        logging.warning("No valid samples found after processing. Exiting.")
        return

    # 3. Create Hugging Face Datasets
    correct_ds = datasets.Dataset.from_list(correct_list) if correct_list else None
    incorrect_ds = datasets.Dataset.from_list(incorrect_list) if incorrect_list else None

    # 4. Define dataset names on the Hub
    correct_ds_name = f"round_{args.round_num}_correct"
    incorrect_ds_name = f"round_{args.round_num}_incorrect"

    # 5. Push to Hub
    push_success = True
    if correct_ds:
        try:
            logging.info(f"Pushing {correct_ds_name} ({len(correct_ds)} samples) to {args.hub_repo_id}...")
            correct_ds.push_to_hub(args.hub_repo_id, config_name=correct_ds_name, private=args.repo_private)
            logging.info(f"Successfully pushed {correct_ds_name}.")
        except Exception as e:
            logging.error(f"Error pushing {correct_ds_name}: {e}")
            push_success = False
            time.sleep(2)  # Allow potential cleanup before next push

    if incorrect_ds:
        try:
            logging.info(f"Pushing {incorrect_ds_name} ({len(incorrect_ds)} samples) to {args.hub_repo_id}...")
            incorrect_ds.push_to_hub(
                args.hub_repo_id,
                config_name=incorrect_ds_name,
                private=args.repo_private,
            )
            logging.info(f"Successfully pushed {incorrect_ds_name}.")
        except Exception as e:
            logging.error(f"Error pushing {incorrect_ds_name}: {e}")
            push_success = False

    if push_success:
        logging.info(f"Data storage complete for Round {args.round_num}.")
        # 6. Cleanup old data only if push was generally successful
        cleanup_old_hub_data(args.hub_repo_id, args.round_num, args.max_rounds_to_keep)
    else:
        logging.error("Data storage failed for one or more datasets. Skipping cleanup.")


if __name__ == "__main__":
    main()
